services:
  app:
    build: .
    volumes:
        - .:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:alpine
    volumes:
        - .:/var/www/html
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagamento
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
